name: Develop pipeline deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 18.17.1
      - name: Install deps
        run: npm install
      - name: Lint
        run: npm run lint
