name: Develop pipeline deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install --no-audit
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
