name: Say hello

on:
  push:
    branches:
      - develop

jobs:
  hello_world:
  runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: |
          echo "Hola desde el pipeline!"
